### ISSUE TITLE
initial_trie_root is never `Some`

### ISSUE THREAD

**Issue by marijanp** [cspr-rad/kairos#135]
https://github.com/cspr-rad/kairos/blob/2dd35183d7ad0112cc55500d429a67c12a11f5ef/demo-contract-tests/tests/test_fixture/mod.rs#L34
We should add a test

**Comment by Avi-D-coder** [comment]
It is in testing. If I test from a randomly generated trie I have to provide it with the pre-batch root.

**Comment by marijanp** [comment]
You're right, I grepped for a explicit `Some`
