### ISSUE TITLE
Nix: False positives in E2E tests

### ISSUE THREAD

**Issue by koxu1996** [cspr-rad/kairos#63]
Nix's e2e tests relying on `curl` SHOULD be already broken at least twice - for example the following PRs successfully passed CI checks, even they changed request body in incompatible way:

- https://github.com/cspr-rad/kairos/pull/32
- https://github.com/cspr-rad/kairos/pull/53

**Comment by koxu1996** [comment]
By default, receiving a 500 Internal Server Error would result in an exit code of 0 (indicating no error in the `curl` command itself). In order to detect server errors, `--fail` / `--fail-with-body` should be provided.

@marijanp already submitted fix in #59.

**Comment by koxu1996** [comment]
Fixed in #59.

**Comment by marijanp** [comment]
> By default, receiving a 500 Internal Server Error would result in an exit code of 0 (indicating no error in the `curl` command itself). In order to detect server errors, `--fail` / `--fail-with-body` should be provided.
> 
> @marijanp already submitted fix in #59.

Curl didn't respond with a 500 error code because our server was beghind an nginx server, which returned a html containing a 301 permamently moved error message. This returns a 0 exit code.

**Comment by koxu1996** [comment]
@marijanp You are wrong :roll_eyes:. Here is proof that code 301 is not an error, even if you add `--fail-with-body`:

```
$ curl --fail-with-body -v bankier.pl
*   Trying 104.22.72.129:80...
* Connected to bankier.pl (104.22.72.129) port 80
> GET / HTTP/1.1
> Host: bankier.pl
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Thu, 04 Apr 2024 12:14:44 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: max-age=3600
< Expires: Thu, 04 Apr 2024 13:14:44 GMT
< Location: https://bankier.pl/
< Server: cloudflare
< CF-RAY: 86f1384afb448869-WAW
<
* Connection #0 to host bankier.pl left intact
$ echo $?
0
```

Also, I didn't say server returned code 500, but only stated that error checking was done incorrectly:

> receiving a 500 Internal Server Error **WOULD** result in an exit code of 0

**Comment by marijanp** [comment]
@koxu1996 so what is wrong about my statement? I said it returned 0, because curl fetched a 301. A 0 indicates success.

**Comment by koxu1996** [comment]
Maybe you are suggesting there is another CI issue?

**Comment by marijanp** [comment]
![scrot-2024-04-04_2317x294](https://github.com/cspr-rad/kairos/assets/13599169/13b34119-17dc-4340-abc9-6cdfc4bda7ca)
There were two issues, another one was that I forced SSL in our production config. And I had to override that in the test to get rid of the permament/y moved 301 status code. That's the first reason it didn't error.

**Comment by marijanp** [comment]
So even adding `--fail-with-body` was not the only problem with it:
![scrot-2024-04-04_2540x292](https://github.com/cspr-rad/kairos/assets/13599169/f6378356-499f-4137-b627-17a5ce71aa26)

**Comment by marijanp** [comment]
https://github.com/cspr-rad/kairos/commit/4e61d681c691809a6010af71ac96583db8e9bc81

**Comment by koxu1996** [comment]
Like I said, another CI issue - not related with `curl` and fixed without context.
